general:
  s3_bucket: ss-48hrs

project:
  name:  design-patterns
  parameters:
    InstanceType: t3.xlarge
    WorkshopCodeURL: https://amazon-dynamodb-labs.com/assets/workshop.zip
    VPCSelection: CreateNewVPC
  s3_enable_sig_v2: false
  s3_object_acl: private
  template: ./lab.yaml
tests:
  ee:
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-west-2
      - eu-central-1
      - sa-east-1
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ap-northeast-2
