name: ValidatePR

permissions:
  id-token: write
on:
  pull_request:
    branches: [ master ]

jobs:
  buildAndVerify:
    runs-on: ubuntu-latest
    env:
      STEP_S3_BUCKET: 'test.amazon-dynamodb-labs.com'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: '0'
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Pull preview build
      run: aws s3 sync s3://amazon-dynamodb-labs-static/build/ . && chmod +x preview_build
    - name: Build Assets
      run: python3 ./.github/scripts/build-assets.py
